rootProject.name = 'air-bridge'
include 'common', 'capture', 'packager', 'query', 'slide', 'sender', 'receiver'

project(':common').projectDir = file('libs/common')
project(':capture').projectDir = file('libs/capture')
project(':packager').projectDir = file('libs/packager')
project(':query').projectDir = file('libs/query')
project(':slide').projectDir = file('libs/slide')
project(':sender').projectDir = file('apps/sender')
project(':receiver').projectDir = file('apps/receiver')
